version: "3"

services:
  traefik:
    image: traefik
    restart: always
    command:
      - "--api"
      - "--docker"
      - "--docker.watch"
      - "--docker.swarmMode"
      - "--docker.domain=${TRAEFIK_DOMAIN}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
       - "traefik.backend=traefik"
       - "traefik.docker.network=traefik_public"
       - "traefik.frontend.rule=Host:traefik.${TRAEFIK_DOMAIN}"
       - "traefik.port=8080"
       - "traefik.frontend.auth.basic.users=${TRAEFIK_AUTH_USERNAME}:${TRAEFIK_AUTH_PASSWORD}"

networks:
  public:
    driver: overlay
